#ifndef GPIO_BITAXE_H_
#define GPIO_BITAXE_H_

#define GPIO_BUTTON_BOOT GPIO_NUM_0
#define GPIO_ASIC_RESET  GPIO_NUM_1
#define GPIO_ASIC_ENABLE GPIO_NUM_10
#define GPIO_PLUG_SENSE  GPIO_NUM_12
#define GPIO_I2C_SDA     GPIO_NUM_47
#define GPIO_I2C_SCL     GPIO_NUM_48

#endif /* GPIO_BITAXE_H_ */
